//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferingLine
    {
        public int OfferingLineId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int OfferingId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public int StatusId { get; set; }
    
        public virtual Offering Offering { get; set; }
    }
}
