//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offering
    {
        public Offering()
        {
            this.OfferingLines = new HashSet<OfferingLine>();
        }
    
        public int OfferingId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> OfferingYear { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> MethodId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Goods { get; set; }
        public Nullable<System.DateTime> ReceiptIssuedDate { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public Nullable<System.DateTime> YTDReceiptIssuedDate { get; set; }
        public Nullable<int> YTDReceiptId { get; set; }
        public int StatusId { get; set; }
        public int SignatureUserId { get; set; }
        public Nullable<int> ReceiptTypeId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OfferingLine> OfferingLines { get; set; }
    }
}
