//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int UserTypeId { get; set; }
        public string SignatureImageName { get; set; }
        public System.DateTime TakenOnDateTime { get; set; }
        public string SignatureImageExtension { get; set; }
        public byte[] SignatureImageBytes { get; set; }
        public int StatusId { get; set; }
    }
}
